-- Create a table for logging downloads
create table public.downloads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  original_url text not null,
  format text,
  quality text,
  filename text,
  ip_address text,
  status text default 'completed'
);

-- Enable Row Level Security (RLS) if you want to restrict access
alter table public.downloads enable row level security;

-- Policy: Allow inserts from anyone (anon key) - USE CAREFULLY or better handle in backend
-- Since we insert from backend (service role usually), RLS might not block it if using service role key.
-- But standard anon key needs this:
create policy "Enable insert for everyone" on public.downloads for insert with check (true);

-- Policy: Allow select only for authenticated users (dashboard admins)
create policy "Enable read access for authenticated users only" on public.downloads for select using (auth.role() = 'authenticated');
